hugo-links-move-for-4.10-community
corda/corda-docs-portal pull request #1147
Opened 2023-03-06 17:46 UTC by colin-hillis

All remaining relative links preceded by ../ have been updated to use Hugo links for 4.10 Community:

Approximately 100 links or slightly more in total, across approx 80 files, with 18-20 broken links identified by the Hugo link checker.

2023-03-06 17:58 UTC, paulmoloneyr3 requested changes

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +The Cordformation plugin can also sign CorDapp JARs when [deploying a set of nodes](./generating-a-node.md).
Should this be relref too?

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +* Know [what a CorDapp is]({{< relref "../../../../../../en/platform/corda/4.8/enterprise/cordapps/cordapp-overview.md" >}}).
```suggestion
* Know [what a CorDapp is]({{< relref "../enterprise/cordapps/cordapp-overview.md" >}}).
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +* Set up your [development environment]({{< relref "../../../../../../en/platform/corda/4.8/enterprise/cordapps/getting-set-up.md" >}}).
```suggestion
* Set up your [development environment]({{< relref "../enterprise/cordapps/getting-set-up.md" >}}).
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +* Run a [sample CorDapp]({{< relref "../../../../../../en/platform/corda/4.8/enterprise/cordapps/tutorial-cordapp.md" >}}) to see Corda in action (optional).
```suggestion
* Run a [sample CorDapp]({{< relref "../enterprise/cordapps/tutorial-cordapp.md" >}}) to see Corda in action (optional).
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +flows (see [Versioning]({{< relref "../../../../../../en/platform/corda/4.8/enterprise/cordapps/versioning.md" >}})).
```suggestion
flows (see [Versioning]({{< relref "../enterprise/cordapps/versioning.md" >}})).
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/getting-set-up.md
> +{{< note >}} Visit the [platform support matrix]({{< relref "../../../../../en/platform/corda/4.8/enterprise/platform-support-matrix.md" >}}) to check the latest third-party application versions supp
```suggestion
{{< note >}} Visit the [platform support matrix]({{< relref "release-platform-support-matrix.md" >}}) to check the latest third-party application versions supported by Corda. {{< /note >}}
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/secure-coding-guidelines.md
> +* [Writing flows]({{< relref "../../../../../en/platform/corda/4.8/enterprise/flow-state-machines.md" >}})
```suggestion
* [Writing flows]({{< relref "../enterprise/flow-state-machines.md" >}})
```

2023-03-06 17:58 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.10/community/tutorial-cordapp.md
> +You can connect directly to your node’s database to see its stored states, transactions, and attachments. Follow the instructions in [Node database]({{< relref "../../4.8/enterprise/node/operating/no
```suggestion
You can connect directly to your node’s database to see its stored states, transactions, and attachments. Follow the instructions in [Node database]({{< relref "../enterprise/node/operating/node-database.md" >}}).
```

2023-03-06 18:08 UTC, yarivus requested changes
@colin-hillis 
I see several inconsistencies: 

1. You use relref but don't remove the .md (as observed in other PRs)
2. Some of the links next to the changes were not changed using relref (@paulmoloneyr3 highlighted some in his comments)
3. Following another PR review earlier - we reference enterprise links while in the community pages (?!)

2023-03-06 19:08 UTC, colin-hillis commented on content/en/platform/corda/4.10/community/cordapp-build-systems.md
> +The Cordformation plugin can also sign CorDapp JARs when [deploying a set of nodes](./generating-a-node.md).
Good spot. This was a manual edit.

2023-03-06 19:19 UTC, colin-hillis commented
> @colin-hillis I see several inconsistencies:
> 
> 1. You use relref but don't remove the .md (as observed in other PRs)
> 2. Some of the links next to the changes were not changed using relref (@paulmoloneyr3 highlighted some in his comments)
> 3. Following another PR review earlier - we reference enterprise links while in the community pages (?!)

1. So the ones missing .md in the very first merge for one single page....that was my mistake to not include .md. It actually makes no difference, but it is more a consistency thing.
2. Paul's changes to the overuse of ../../ are not in the scope of this. This is to convert the link types, but the use of far too many ../s has already been highlighted as a follow up project in the Confluence page for this work. So Paul's changes (although I have accepted them), are not in scope.
3. This was the focus of a previous effort by Paul, but lots of links were missed because we didn't have a reliable link checker. I identified 16-18 earlier. So this roll out is helping the problem.
4. Additionally the scope of this above commits was for all links starting ../ A further commit will follow to deal with links starting ./. In fact there are several other follow ups to get everything right (all of which are on the confluence page), but this is 100% iterative. So just ../ links first.

It is far too risky to try to do it all at once.

2023-03-06 22:26 UTC, colin-hillis commented
For clarity on scope, see: https://r3-cev.atlassian.net/wiki/spaces/TW/pages/4390879344/Hugo+Links#Steps-for-Changes

2023-03-07 09:38 UTC, yarivus commented
> > @colin-hillis I see several inconsistencies:
> > 
> > 1. You use relref but don't remove the .md (as observed in other PRs)
> > 2. Some of the links next to the changes were not changed using relref (@paulmoloneyr3 highlighted some in his comments)
> > 3. Following another PR review earlier - we reference enterprise links while in the community pages (?!)
> 
> 1. So the ones missing .md in the very first merge for one single page....that was my mistake to not include .md. It actually makes no difference, but it is more a consistency thing.
> 2. Paul's changes to the overuse of ../../ are not in the scope of this. This is to convert the link types, but the use of far too many ../s has already been highlighted as a follow up project in the Confluence page for this work. So Paul's changes (although I have accepted them), are not in scope.
> 3. This was the focus of a previous effort by Paul, but lots of links were missed because we didn't have a reliable link checker. I identified 16-18 earlier. So this roll out is helping the problem.
> 4. Additionally the scope of the above commits was for all links starting ../ A further commit will follow to deal with links starting ./. In fact there are several other follow ups to get everything right (all of which are on the confluence page), but this is 100% iterative. I initially wanted to just do ../, but I will do ./ now too. The other 6 or 7 links types and edge cases will have to wait though for the next effort.
> 
> It is far too risky to try to do them all at once.

@colin-hillis there are still 'community' pages referencing 'enterprise' links.
I haven't understood from your reply whether that is intended, and if not what's the plan of fixing this inconsistency ?
Is the plan to do it in a following PR ?

2023-03-07 22:02 UTC, colin-hillis commented
Hi Yariv,

Whilst some were identified and fixed because of they were just 404s, if some of Paul's links between Community and Enterprise are actually correct links to begin with, this effort of mine is not going to spot them. That is out of scope.

The purpose of this process is to migrate to the recommended Hugo links and some existing broken links will naturally be fixed along the way. But the correction of already working links is not going to be solved by this. However, I have another idea for Paul to try, which will find all instances of the mentioned cross-links and allow them to be fixed.  I can talk to @paulmoloneyr3 about this separately.

2023-03-08 10:55 UTC, yarivus commented
> Hi Yariv,
> 
> Whilst some were identified and fixed because of they were just 404s, if some of Paul's links between Community and Enterprise are actually correct links to begin with, this effort of mine is not going to spot them. That is out of scope.
> 
> The purpose of this process is to migrate to the recommended Hugo links and some existing broken links will naturally be fixed along the way. But the correction of already working links is not going to be solved by this. However, I have another idea for Paul to try, which will find all instances of the mentioned cross-links and allow them to be fixed. I can talk to @paulmoloneyr3 about this separately.

OK - I understand that the community pages referencing enterprise is out of scope here for this PR.
@paulmoloneyr3 - please create a separate PR for that problem.

2023-03-08 10:55 UTC, yarivus approved these changes
LGTM

2023-03-08 11:18 UTC, colin-hillis commented
@paulmoloneyr3 once I am back, let's chat about this before going ahead please. It has been like this for weeks, so another day will be ok. Cheers Paul.

2023-03-08 11:20 UTC, paulmoloneyr3 commented
> @paulmoloneyr3 once I am back, let's chat about this before going ahead please. It has been like this for weeks, so another day will be ok. Cheers Paul.

Talk to you then!

2023-03-08 11:45 UTC, paulmoloneyr3 approved these changes

2023-03-08 11:53 UTC, merged