smart contracts clarifications
corda/corda-docs-portal pull request #1197
Opened 2023-03-21 12:12 UTC by nadinequinr3

2023-03-21 12:35 UTC, paulmoloneyr3 approved these changes

2023-03-21 12:41 UTC, colin-hillis requested changes
Couple of small changes. Take or leave the first one.

2023-03-21 12:41 UTC, colin-hillis commented on content/en/platform/corda/5.0-beta/developing/ledger/smart-contracts.md
> +* Check that a [time window]({{< relref "./time-windows.md" >}}) exists and that time points mentioned in states fall within this time window.
^^^ assuming that 'States' is another field or function ^^^

2023-03-21 13:34 UTC, blsemo requested changes
While not wrong, I am not 100% convinced this is worded the most understandable way.

2023-03-21 13:34 UTC, blsemo commented on content/en/platform/corda/5.0-beta/developing/ledger/smart-contracts.md
> +* Check that a [time window]({{< relref "./time-windows.md" >}}) exists and that time points mentioned in states fall within this time window.
I am not sure I would word it that specifically - that was just the most obvious example. The contract verification code can check that the time window matches the expectations for the given transaction, e.g. that a point in time mentioned in one of the states (inputs, outputs, references) falls within the time window.
Also, a time window always exists, as in Corda 5, it's mandatory for all UTXO transactions. You wouldn't even get this far without one.

2023-03-21 13:34 UTC, blsemo commented on content/en/platform/corda/5.0-beta/developing/ledger/smart-contracts.md
> +To enable the nodes on a network to reach consensus about a proposed update to the ledger, transaction verification must be deterministic. This means that contracts must always accept or reject a giv
Hmm - that last sentence is a bit misleading, it's always a reject or an accept, the point being that the result can't change on further validations once it's accepted or rejected.

2023-03-22 13:02 UTC, nadinequinr3 commented
@blsemo I've made some updates, if you could re-review, please.

2023-03-22 14:34 UTC, yarivus approved these changes
LGTM

2023-03-24 11:24 UTC, yarivus approved these changes
LGTM - clean merge

2023-03-31 14:10 UTC, blsemo approved these changes
LGTM

2023-04-01 18:30 UTC, yarivus approved these changes
LGTM - clean merge

2023-04-03 08:45 UTC, yarivus approved these changes
LGTM - clean merge

2023-04-04 14:42 UTC, colin-hillis approved these changes
LGTM

2023-04-04 14:54 UTC, merged