initial restructuring
corda/corda-docs-portal pull request #1211
Opened 2023-03-24 18:11 UTC by nadinequinr3

2023-03-26 07:36 UTC, yarivus approved these changes
Lgtm

2023-03-27 08:19 UTC, yarivus requested changes

2023-03-27 08:19 UTC, yarivus commented on content/en/platform/corda/5.0-beta/release-notes/release-notes-c5-2.0.md
> +| **CorDapp Development**                      | **Java API** - The Kotlin API has been replaced with a Java API. As a result, existing CorDapps must be written. Kotlin and Java developers can now us
```suggestion
| **CorDapp Development**                      | **Java API** - The Kotlin API has been replaced with a Java API. As a result, existing CorDapps must be rewritten. Kotlin and Java developers can now use this API to build CorDapps. |
```
Or ...
```suggestion
| **CorDapp Development**                      | **Java API** - The Kotlin API has been replaced with a Java API. As a result, existing CorDapps must be adapted. Kotlin and Java developers can now use this API to build CorDapps. |
```

2023-03-27 08:22 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0-beta/release-notes/release-notes-c5-2.0.md
> +|                                              | **Operational Statuses** - Four new operational statuses have been added for virtual nodes to provide fine-grained control over its flows and what com
```suggestion
|                                              | **Operational Statuses** - Four new operational statuses have been added for virtual nodes to provide fine-grained control over their flows and what components they can interact with: <li>`flowOperationalStatus` — describes a virtual node's ability to start new flows. </li> <li>`flowP2pOperationalStatus` — describes a virtual node's ability to communicate with peers.</li> <li>`flowStartOperationalStatus`  — describes a virtual node's ability to run flows, to have checkpoints, and to continue in-progress flows. </li> <li> `vaultDbOperationalStatus` —  describes a virtual node's ability to perform persistence operations on the virtual node's vault. </li> These four statuses replace the existing `state` field. The `GET virtualnode` now returns the status of each of the four operational characteristics. Maintenance mode has been updated to disable all four of these new operational statuses. You can set this mode using the existing change virtual node state endpoint: `/api/v1/virtualnode/{virtualNodeShortHash}/state/{newState}`. 
```

2023-03-27 08:38 UTC, AnnaK-R3 approved these changes

2023-03-27 08:39 UTC, yarivus approved these changes
LGTM

2023-03-27 10:01 UTC, colin-hillis requested changes

2023-03-27 10:02 UTC, colin-hillis commented
I have tried a few approaches to merging cells for the first column, but nothing has worked so far. This is perhaps something that we can circle back on soon, but for now, there are bigger priorities.

2023-03-27 10:40 UTC, merged