use "Next-Gen"
corda/corda-docs-portal pull request #1212
Opened 2023-03-27 08:01 UTC by nadinequinr3

2023-03-27 08:28 UTC, yarivus reviewed
LGTM 
Although I'm confused why Beta2 == NextGen as opposed to Corda5 == NextGen 
And if so, it should be Corda Next-Gen: Beta 2 (as it's the 2nd beta of Next-Gen Corda)

2023-03-27 08:29 UTC, nadinequinr3 commented
> LGTM Although I'm confused why Beta2 == NextGen as opposed to Corda5 == NextGen And if so, it should be Corda Next-Gen: Beta 2 (as it's the 2nd beta of Next-Gen Corda)

Good point. I'll tweak. Thanks.

2023-03-27 08:32 UTC, paulmoloneyr3 submitted a review, later dismissed

2023-03-27 08:37 UTC, yarivus approved these changes
LGTM

2023-03-27 09:37 UTC, milan-khan commented on content/en/platform/corda/5.0-beta/_index.md
> +## Corda 5.0: Next-Gen Corda - Beta 2
This seems a little clumsy to me, almost as though we're naming something twice. I think it should be "Next-Gen Corda - Beta 2"

2023-03-27 09:51 UTC, milan-khan commented on themes/doks/layouts/index.html
> +              <h3 class="card-title">Corda 5.0: Next-Gen Corda - Beta 2</h3>
We should say "Corda 5.0 - Beta 2" or "Next-Gen Corda - Beta 2"

2023-03-27 09:56 UTC, milan-khan requested changes
We should say "Corda 5.0 - Beta 2" or "Next-Gen Corda - Beta 2"

2023-03-27 11:59 UTC, nadinequinr3 commented
> We should say "Corda 5.0 - Beta 2" or "Next-Gen Corda - Beta 2"

I was trying to make the link that Corda 5 and Corda Next-Gen are the same things.

2023-03-27 12:38 UTC, colin-hillis commented
In principle, using Next-Gen as the name (albeit temporary) is confusing and it will be for customers too. It would have been more sensible to have 'Next-Gen' worked into a tag line for Beta 2.0, but not the name itself. I get it that the new product requires marketing for certain types of communication, but for the technical docs, it is 100% going to be confusing for customers to change from **Corda Next Gen** to **Corda 5.0** in the GA release, or even GA+1. 

If it is the case that we have to run with this, I am not sure if this is the extent of the locations where it is to be changed....perhaps we can keep it to as few as possible, so that there are not dozens of locations where it has to be manually changed when we revert back to Corda 5 again. 

Whatever is decided on the wording front, I think it is important to also include 5 or 5.0 to reduce the chance of confusion, when we decide to change the name back to 5 or 5.0 again.

2023-03-27 15:23 UTC, milan-khan commented
@colin-hillis @nadinequinr3 yes "Next-Gen Corda 5.0 - Beta 2.0" works. I think we can have it in the one place i.e. in this landing page. It looks a bit long-winded to be using in many places.

2023-03-28 09:16 UTC, yarivus approved these changes
LGTM

2023-03-28 09:58 UTC, paulmoloneyr3 approved these changes

2023-03-28 10:03 UTC, colin-hillis approved these changes
LGTM

2023-03-28 10:39 UTC, merged