DOC-5071: Clarified the steps for creating RBAC roles manually
corda/corda-docs-portal pull request #1242
Opened 2023-03-30 09:48 UTC by AnnaK-R3

2023-03-30 14:03 UTC, yarivus approved these changes
LGTM

2023-03-31 05:40 UTC, ShYogesh-R3 submitted a review, later dismissed

2023-03-31 08:38 UTC, paulmoloneyr3 requested changes

2023-03-31 08:38 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/manual.md
> +<API-ENDPOINT> that should be a URL where the Corda API is accessible, either via a load balancer or by forwarding port 8888 from one of the REST worker pods.
```suggestion
<API-ENDPOINT> as a parameter. That value should be a URL where the Corda API is accessible, either via a load balancer or by forwarding port 8888 from one of the REST worker pods.
```

2023-03-31 08:51 UTC, paulmoloneyr3 approved these changes

2023-03-31 08:52 UTC, merged

2023-03-31 08:56 UTC, yarivus reviewed
thx @AnnaK-R3