DOC-5174: Permissions
corda/corda-docs-portal pull request #1275
Opened 2023-04-18 10:05 UTC by AnnaK-R3

2023-04-18 10:35 UTC, yarivus requested changes

2023-04-18 10:35 UTC, yarivus commented on content/en/platform/corda/5.0-beta/developing-and-operating/permissions/overview.md
> +Corda 5 implements role-based access control (RBAC) permission system, also known as role-based security, as a mechanism to restrict system access.
```suggestion
Corda 5 implements role-based access control (RBAC) permissions system, also known as role-based security, as a mechanism to restrict system access.
```

2023-04-18 10:35 UTC, yarivus commented on content/en/platform/corda/5.0-beta/developing-and-operating/permissions/permission-templates.md
> +By default, when a cluster starts there is a single "admin" account auto-created which can do everything.
be more specific - rather than "which can do everything"

2023-04-20 09:14 UTC, AnnaK-R3 commented
Closing this PR as I created a new one: https://github.com/corda/corda-docs-portal/pull/1280

2023-04-20 09:14 UTC, closed without merging