Niamh25/doc 5218/getting started gradle plugin images update
corda/corda-docs-portal pull request #1295
Opened 2023-04-25 15:13 UTC by Niamh25

Updated three images in the CSDE and configuring the Network participants. Added new image to the configuring the CSDE section.

2023-04-25 15:17 UTC, Niamh25 commented
Preview found here: 
https://niamh.preview.docs.r3.com/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.html

2023-04-25 15:25 UTC, tlawson3 requested changes

2023-04-25 15:25 UTC, tlawson3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +{{< figure src="configure-CSDE-build-gradle-block.png" figcaption="CSDE build gradle" alt="CSDE build gradle block in IntelliJ for CSDE project" >}}
Can we change the caption to 

> Configure the CSDE plugin via the build.gradle file

2023-04-26 09:10 UTC, yarivus reviewed
I see pending comments from @tlawson3

2023-04-26 10:30 UTC, tlawson3 approved these changes
💯

2023-04-26 10:43 UTC, AnnaK-R3 submitted a review, later dismissed

2023-04-26 12:32 UTC, amiegrace12 approved these changes

2023-04-26 12:33 UTC, merged

2023-04-26 17:43 UTC, yarivus reviewed
thx @Niamh25