DOC-5352: Added content to the deploying section
corda/corda-docs-portal pull request #1357
Opened 2023-05-11 10:11 UTC by AnnaK-R3

2023-05-11 11:01 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/deploying.md
> +This page describes how to deploy Corda 5 Beta.
```suggestion
This page describes how to deploy Corda 5.
```

2023-05-11 13:37 UTC, nadinequinr3 requested changes
There are also some unnecessary line breaks that would be nice to fix

2023-05-11 13:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/bootstrapping.md
> +The following command specifies that the `CONFIG`, `RBAC` and `CRYPTO` schema should be used for the corresponding components and generates the files in the directory `/tmp/db`:
```suggestion
The following command specifies that the `CONFIG`, `RBAC`, and `CRYPTO` schema should be used for the corresponding components and generates the files in the directory `/tmp/db`:
```

2023-05-11 13:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/deploying.md
> +All the necessary [prerequisites](prerequisites.md) must have been satisfied before Corda is deployed.
```suggestion
All the necessary [prerequisites]({{< relref "prerequisites.md" >}}) must have been satisfied before Corda is deployed.
```

2023-05-11 13:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/prerequisites.md
> +There are three prerequisites to Corda deployment process:
```suggestion
There are three prerequisites to the Corda deployment process:
```
or 
```suggestion
There are three prerequisites to Corda deployment:
```

2023-05-11 13:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/prerequisites.md
> +If bootstrapping manually, an additional virtual node user will still need the ability to create schemas dynamically at runtime.
maybe link to the bootstrapping page?

2023-05-11 13:42 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/_index.md
> +The following section describes the prerequisites and the process for deploying Corda.
```suggestion
This section describes the prerequisites and the process for deploying Corda.
```

2023-05-11 14:34 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deploying/prerequisites.md
> +If bootstrapping manually, an additional virtual node user will still need the ability to create schemas dynamically at runtime.
```suggestion
If [bootstrapping manually](bootstrapping.md), an additional virtual node user will still need the ability to create schemas dynamically at runtime.
```

2023-05-11 14:37 UTC, nadinequinr3 approved these changes

2023-05-11 17:12 UTC, yarivus approved these changes
LGTM

2023-05-12 10:24 UTC, nadinequinr3 approved these changes

2023-05-12 10:25 UTC, merged