DOC-4690: Define basic install resources
corda/corda-docs-portal pull request #1371
Opened 2023-05-16 15:17 UTC by AnnaK-R3

2023-05-16 15:28 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-16 16:08 UTC, davidcurrie approved these changes
LGTM :shipit:

2023-05-17 20:52 UTC, vadanx submitted a review, later dismissed
LGTM

2023-05-18 09:17 UTC, paulmoloneyr3 requested changes

2023-05-18 09:17 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/deploy-corda-cluster.md
> +When it comes to AWS topology, we recommend the following initial configuration:
```suggestion
Regarding AWS topology, we recommend the following initial configuration:
```

2023-05-18 09:17 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/deploy-corda-cluster.md
> +* MSK: For a cluster with a single replica of each worker, and a topic replica count of three, a Kafka cluster of three
```suggestion
* MSK: For a cluster with a single replica of each worker and a topic replica count of three, a Kafka cluster of three
```

2023-05-18 09:28 UTC, yarivus approved these changes
LGTM

2023-05-18 09:53 UTC, paulmoloneyr3 approved these changes

2023-05-18 09:54 UTC, merged