Nadinequinr3/doc 5424/how to deploy corda enterprise
corda/corda-docs-portal pull request #1403
Opened 2023-05-29 11:39 UTC by nadinequinr3

2023-05-29 13:58 UTC, yarivus requested changes

2023-05-29 13:58 UTC, yarivus commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
> +If you have access to Docker Hub, you can download the Corda Helm chart using the following command for Corda Communnity:
```suggestion
If you have access to Docker Hub, you can download the Corda Helm chart using the following command for Corda Community:
```

2023-05-30 08:19 UTC, yarivus submitted a review, later dismissed
LGTM

2023-05-30 09:01 UTC, davidcurrie reviewed
Looks good from my side.

@ronanbrowne - can you confirm that the names for the TAR files are correct and that customers will now pull the charts directly from Artifactory?

2023-05-30 13:44 UTC, yarivus approved these changes
LGTM

2023-05-31 16:07 UTC, mcgovc approved these changes
LGTM

2023-05-31 16:20 UTC, amiegrace12 approved these changes

2023-05-31 16:38 UTC, merged