Niamh25/DOC-5179/Observability-probe-changes
corda/corda-docs-portal pull request #1421
Opened 2023-06-01 15:50 UTC by Niamh25

Fixed indentation and rephrased some sentences.

2023-06-01 16:22 UTC, amiegrace12 requested changes

2023-06-01 16:22 UTC, amiegrace12 commented on content/en/platform/corda/5.0/deploying-operating/observability/k8-probes.md
> +These poll the status of the the worker’s internal component registry.
```suggestion
These poll the status of the worker’s internal component registry.
```

2023-06-01 16:24 UTC, amiegrace12 approved these changes

2023-06-01 16:27 UTC, merged

2023-06-02 14:46 UTC, yarivus reviewed
thx @Niamh25