DOC-5431: Manual boostrapping typo
corda/corda-docs-portal pull request #1443
Opened 2023-06-08 14:01 UTC by AnnaK-R3

2023-06-08 14:42 UTC, nadinequinr3 requested changes

2023-06-08 15:47 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
>      {{< tabs name="vNode-example">}}
Yes, I noticed that this was happening for all code blocks in this section. I fixed the indentation for all of them and the ``` are not displaying anymore: https://anna.preview.docs.r3.com/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.html

2023-06-08 19:32 UTC, nadinequinr3 approved these changes

2023-06-08 20:05 UTC, nadinequinr3 requested changes

2023-06-09 08:14 UTC, nadinequinr3 approved these changes

2023-06-09 08:17 UTC, merged

2023-06-09 09:41 UTC, yarivus reviewed
thx @AnnaK-R3