Niamh25/doc 5544/move utxo extensions
corda/corda-docs-portal pull request #1506
Opened 2023-06-22 15:39 UTC by Niamh25

Moves the UTXO advanced ledger extensions under the UTXO API folder. Fixed table to add more space to first column.

2023-06-22 15:58 UTC, Niamh25 commented
Preview site here: https://niamh.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application/ledger/utxo-ledger/utxo-advanced-ledger-extensions.html

2023-06-22 16:00 UTC, nadinequinr3 requested changes
I think the `ledger` folder should just be in the `api` folder (not `api/application`)? It isn't displayed under https://niamh.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html

2023-06-23 09:23 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/_index.md
> +# net.corda.v5.ledger.utxo
shouldn't there be {{childpages}} here ?

2023-06-23 09:23 UTC, yarivus reviewed
see 1 comment

2023-06-23 09:55 UTC, yarivus reviewed
still pending comments

2023-06-23 10:22 UTC, nadinequinr3 approved these changes

2023-06-23 10:33 UTC, merged

2023-06-23 13:53 UTC, yarivus reviewed
thnx @Niamh25