DOC-5495: Updated PostgreSQL section in CENM databases doc
corda/corda-docs-portal pull request #1519
Opened 2023-06-27 16:46 UTC by amiegrace12

- Added options for creating a CENM service instance user in PostgreSQL using a custom schema name.
- Added escape characters to <host>, <port>, <sid> as they weren't showing on the docs site.

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/1.5/cenm/database-set-up.html#postgresql

2023-06-27 19:09 UTC, yarivus approved these changes
LGTM

2023-07-06 07:30 UTC, yarivus requested changes

2023-07-06 07:30 UTC, yarivus commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +Replace the placeholders *host*,*port* and *sid* with appropriate values. For a basic Oracle installation, the default *sid* value is `xe`.
```suggestion
Replace the placeholders *host*, *port* and *sid* with appropriate values. For a basic Oracle installation, the default *sid* value is `xe`.
```

2023-07-06 08:30 UTC, yarivus approved these changes
LGTM

2023-07-06 10:18 UTC, yarivus approved these changes
LGTM

2023-07-06 11:02 UTC, jonathan-jacques approved these changes
I approve the changes.

2023-07-07 09:12 UTC, AnnaK-R3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +If you are creating a CENM service instance user in PostgreSQL using a custom schema name (different from the username), connect to the database as an administrator and run the script above. The last
```suggestion
If you are creating a CENM service instance user in PostgreSQL using a custom schema name (different from the user name), connect to the database as an administrator and run the script above. The last statement in the script - setting the `search_path` - prevents querying the differing [default schema search path](https://www.postgresql.org/docs/9.3/static/ddl-schemas.html#DDL-SCHEMAS-PATH). If you don't have the privileges required to run the script, set the custom schema in the URL in the database configuration section of the `node.conf` file: 
```

2023-07-07 09:12 UTC, AnnaK-R3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +Replace the placeholders *\<host\>* and *\<port\>* in the URL with appropriate values.
```suggestion
Replace the placeholders `\<host\>` and `\<port\>` in the URL with appropriate values.
```

2023-07-07 09:12 UTC, AnnaK-R3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +Replace the placeholders *\<host\>* and *\<port\>* with appropriate values (the default SQL Server port is 1433). By default, the connection to the database is not SSL. To secure the JDBC connection,
```suggestion
Replace the placeholders `\<host\>` and `\<port\>` with appropriate values (the default SQL Server port is 1433). By default, the connection to the database is not SSL. To secure the JDBC connection, refer to [Securing JDBC Driver Applications](https://docs.microsoft.com/en-us/sql/connect/jdbc/securing-jdbc-driver-applications?view=sql-server-2017).
```

2023-07-07 09:12 UTC, AnnaK-R3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +Replace the placeholders *\<host\>*, *\<port\>*, and *\<sid\>* with appropriate values. For a basic Oracle installation, the default *\<sid\>* value is `xe`.
```suggestion
Replace the placeholders `\<host\>`, `\<port\>`, and `\<sid\>` with appropriate values. For a basic Oracle installation, the default `\<sid\>` value is `xe`.
```

2023-07-07 09:12 UTC, AnnaK-R3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +Replace the placeholders *\<host\>* and *\<port\>* with appropriate values.
```suggestion
Replace the placeholders `\<host\>` and `\<port\>` with appropriate values.
```

2023-07-07 09:17 UTC, AnnaK-R3 approved these changes

2023-07-07 09:42 UTC, merged

2023-07-08 08:48 UTC, yarivus reviewed
thx @amiegrace12