DOC-5501: Added tracing page to docs
corda/corda-docs-portal pull request #1532
Opened 2023-07-07 08:44 UTC by AnnaK-R3

2023-07-07 13:02 UTC, josephzunigadaly commented on content/en/platform/corda/5.0/deploying-operating/observability/tracing.md
> +The tracing configuration supported by the Helm chart contains the following information in the `values.yaml` file:
I'm told we haven't documented worker command line parameters. I think we should not document this one alone. Lets remove the command line parameter and focus on the Helm chart.

```suggestion
As a Corda Cluster Operator, you may want to configure a tracing server and sample rate when deploying the Helm chart. The tracing configuration supported by the Helm chart contains the following configuration in the `values.yaml` file:
```

2023-07-08 09:04 UTC, yarivus requested changes

2023-07-08 09:04 UTC, yarivus commented on content/en/platform/corda/5.0/deploying-operating/observability/tracing.md
> +As a Corda Cluster Operator, you may want to configure sample rate when deploying the Helm chart. You can do this using the
```suggestion
As a Corda Cluster Operator, you may want to configure tracing sample rate when deploying the Helm chart. You can do this using the
```

2023-07-11 08:29 UTC, yarivus approved these changes
LGTM

2023-07-11 10:31 UTC, josephzunigadaly approved these changes

2023-07-11 10:44 UTC, amiegrace12 commented on content/en/platform/corda/5.0/deploying-operating/observability/tracing.md
> +  # -- URL for endpoint to send Zipkin-format distributed traces to e.g. http://tempo:9411
```suggestion
  # -- URL for the endpoint to send Zipkin-format distributed traces to for example http://tempo:9411
```

2023-07-11 10:44 UTC, amiegrace12 commented on content/en/platform/corda/5.0/deploying-operating/observability/tracing.md
> +  traces, but in this case amount of tracing data produced can be quite vast.
```suggestion
  traces, but in this case the amount of tracing data produced can be quite vast.
```

2023-07-11 11:01 UTC, amiegrace12 approved these changes

2023-07-11 11:52 UTC, merged

2023-07-11 12:07 UTC, yarivus reviewed
thx @AnnaK-R3