Niamh25/DOC-5287/Update-readme-file
corda/corda-docs-portal pull request #1536
Opened 2023-07-10 16:21 UTC by Niamh25

Added java to files

2023-07-11 09:20 UTC, yarivus requested changes
see my indentation comment

2023-07-11 09:20 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +  @Nullable
you're not consistent with the same indentations ... please create 4 chars indentation like the prev file.

2023-07-11 11:30 UTC, lankydan commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +``` java
All the changes you made below this point should stay as `kotlin`, I can switch them over to `java` anyway.

So we can revert this part, or leave it, I don't mind.

2023-07-11 12:02 UTC, lankydan approved these changes

2023-07-11 12:10 UTC, yarivus requested changes

2023-07-11 12:10 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +  @Nullable
You're still inconsistent in indentation - in 1 file it's 4 spaces and in other it's 2

2023-07-11 15:10 UTC, yarivus reviewed
You still need to fix the consistency of indentations

2023-07-11 16:04 UTC, yarivus requested changes
Indentation is relative - 4 spaces at each level ... 
You've tried to fix it but it's not not relatively indented at all levels of code.
Please work w/ other tech-writers to understand why this is an on-going issue for you ... 
It's taking too much time to review over and over again.

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public List<Class<? extends ChainableContractCommand<?>>> getPermittedCommandTypes() {
```suggestion
  public List<Class<? extends ChainableContractCommand<?>>> getPermittedCommandTypes() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return List.of(Create.class, Update.class, Delete.class);
```suggestion
    return List.of(Create.class, Update.class, Delete.class);  
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    private final NumericDecimal quantity;
```suggestion
  private final NumericDecimal quantity;
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public ExampleFungibleState(@NotNull final NumericDecimal quantity) {
```suggestion
  public ExampleFungibleState(@NotNull final NumericDecimal quantity) {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        this.quantity = quantity;
```suggestion
    this.quantity = quantity;
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public NumericDecimal getQuantity() {
```suggestion
  public NumericDecimal getQuantity() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return quantity;
```suggestion
    return quantity;
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public List<PublicKey> getParticipants() {
```suggestion
  public List<PublicKey> getParticipants() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return List.of(...);
```suggestion
    return List.of(...);
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public boolean isFungibleWith(@NotNull final FungibleState<NumericDecimal> other) {
```suggestion
  public boolean isFungibleWith(@NotNull final FungibleState<NumericDecimal> other) {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return this == other || other instanceof ExampleFungibleState // && other fungibility rules.
```suggestion
    return this == other || other instanceof ExampleFungibleState // && other fungibility rules.
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleIdentifiableState> getContractStateType() {
```suggestion
  public Class<ExampleIdentifiableState> getContractStateType() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return ExampleIdentifiableState.class;
```suggestion
    return ExampleIdentifiableState.class;
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```suggestion
  protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        // Verify additional Delete constraints
```suggestion
    // Verify additional Delete constraints
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleIdentifiableState> getContractStateType() {
```suggestion
  public Class<ExampleIdentifiableState> getContractStateType() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
    @Override
```
```suggestion
  @Override
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +     protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```suggestion
 protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +       // Verify additional Update constraints
```suggestion
   // Verify additional Update constraints
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleFungibleState> getContractStateType() {
```suggestion
  public Class<ExampleFungibleState> getContractStateType() {
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return ExampleFungibleState.class;
```suggestion
    return ExampleFungibleState.class;
```

2023-07-12 09:09 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```suggestion
  protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        // Verify additional Create constraints
```suggestion
    // Verify additional Create constraints
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleFungibleState> getContractStateType() {
```suggestion
  public Class<ExampleFungibleState> getContractStateType() {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return ExampleFungibleState.class;
```suggestion
    return ExampleFungibleState.class;
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```suggestion
  protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        // Verify additional Update constraints
```suggestion
    // Verify additional Update constraints
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @NotNull
```suggestion
  @NotNull
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleIdentifiableState> getContractStateType() {
```suggestion
  public Class<ExampleIdentifiableState> getContractStateType() {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return ExampleIdentifiableState.class;
```suggestion
    return ExampleIdentifiableState.class;
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    @Override
```suggestion
  @Override
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```suggestion
  protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        // Verify additional Create constraints
```suggestion
    // Verify additional Create constraints
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    public Class<ExampleFungibleState> getContractStateType() {
```suggestion
  public Class<ExampleFungibleState> getContractStateType() {
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return ExampleFungibleState.class;
```suggestion
    return ExampleFungibleState.class;
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>  }
```suggestion
  @Override
  protected void onVerify(@NotNull final UtxoLedgerTransaction transaction) {
    // Verify additional Delete constraints
  }
}
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  @Override
  public List<Class<? extends FungibleContractCommand<?>>> getPermittedCommandTypes() {
    return List.of(Create.class, Update.class, Delete.class);
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    private final StateRef id;
```suggestion
  @Nullable
  private final StateRef id;
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  public ExampleIdentifiableState(@Nullable final StateRef id) {
    this.id = id;
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  @Nullable
  public StateRef getId() {
    return id;
  }
```

2023-07-12 09:19 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
```suggestion
  @NotNull
  public List<PublicKey> getParticipants() {
    return List.of(...);
  }
```

2023-07-12 13:55 UTC, AnnaK-R3 approved these changes

2023-07-12 14:04 UTC, lankydan commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
Indentation needs readding.

2023-07-12 14:05 UTC, lankydan commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +    }
Indentation needs readding.

2023-07-13 07:52 UTC, yarivus requested changes
See proposed changes and comments

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>      }
`}` is not on the right column (not indented accordingly

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>  }
This is indented with 4 spaces - while most of the code in the file until now is indented with 2 spaces.
Please be consistent.

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        return listOf(Update::class.java)
```suggestion
    override fun getPermittedCommandTypes(): List<Class<out ExampleOwnableContractCommand>> {
        return listOf(Update::class.java)
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +            }
```suggestion
    override fun getContractStateType(): Class<ExampleOwnableState> {
        return ExampleOwnableState::class.java
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +            }
```suggestion
    override fun verify(transaction: UtxoLedgerTransaction) {
        OwnableConstraints.verifyUpdate(transaction, contractStateType)
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        }
```suggestion
        return listOf(Create::class.java, Delete::class.java)
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        }
```suggestion
    override fun getContractStateType(): Class<ExampleIssuableState> {
        return ExampleIssuableState::class.java
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>      }
```suggestion
        IssuableConstraints.verifyCreate(transaction, contractStateType)
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        }
```suggestion
    override fun getContractStateType(): Class<ExampleIssuableState> {
        return ExampleIssuableState::class.java
    }
```

2023-07-13 07:52 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
> +        }
```suggestion
        IssuableConstraints.verifyDelete(transaction, contractStateType)
    }
```

2023-07-13 09:57 UTC, AnnaK-R3 approved these changes

2023-07-13 12:22 UTC, yarivus requested changes
`object Update : ExampleOwnableContractCommand` section is the last part not indented consistently.
Please fix and we can move to approve

2023-07-13 12:22 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>      }
Only this part is left un-indented with 4 spaces - please re-check the preview

2023-07-14 20:41 UTC, yarivus requested changes

2023-07-14 20:41 UTC, yarivus commented on content/en/platform/corda/5.0/developing-applications/api/ledger/utxo-ledger/utxo-advanced-ledger-extensions/ledger-extensions-api-reference.md
>      object Update : ExampleOwnableContractCommand {
Still not right - if you chose indentation of 4 spaces then every nesting level should have 4 spaces more relative to the previous scope/block of code. So it should look like this:
```
    object Update : ExampleOwnableContractCommand {
  
        override fun getContractStateType(): Class<ExampleOwnableState> {
            return ExampleOwnableState::class.java
        }

        override fun verify(transaction: UtxoLedgerTransaction) {
            OwnableConstraints.verifyUpdate(transaction, contractStateType)
        }
    }
```

2023-07-17 12:56 UTC, yarivus approved these changes
LGTM

2023-07-17 13:02 UTC, merged