CORE-15359  Interopability - Cordapp Api / Developer-Oriented Documentation
corda/corda-docs-portal pull request #1590
Opened 2023-07-26 15:31 UTC by szymonsztuka

Developer-Oriented Documentation:
The developer-oriented documentation, as discussed in this chat, dives into the technical details of Corda Interoperability. It provides a step-by-step guide on implementing Facades, using Facade Proxy objects, and leveraging Corda services to enable communication between Cordapps. This document will help developers understand the concepts, usage, and best practices for building Interoperability-enabled Cordapps.

2023-07-26 16:36 UTC, yarivus approved these changes
LGTM - but needs a review from tech-writers

2023-07-31 10:13 UTC, jmacmahonr3 requested changes
@szymonsztuka, We are missing a section on Facade to Flow mapping.

2023-07-31 10:13 UTC, jmacmahonr3 commented on content/en/interop-raw/_index.md
> +   Facade, and the Corda framework handles the communication with the other Cordapp (Callee Cordapp).
You use Callee alot but im not sure if it's the best term. 

Caller & Receiver might be clearer

2023-08-28 09:15 UTC, yarivus reviewed
pending comments 
checkpoint review

2023-08-28 09:15 UTC, yarivus commented on content/en/interop-raw/interop-api/calling.md
> +   ```
```suggestion
```java
package net.corda.v5.application.interop;

public interface FacadeService {
    <T> T getFacade(String facadeId, Class<T> expectedType, MemberX500Name alias, String interopGroup);
    // ...
}
```
```

2023-08-28 09:15 UTC, yarivus commented on content/en/interop-raw/interop-api/calling.md
> +### Invoking a Façade
```suggestion

### Invoking a Façade
```

2023-08-28 09:15 UTC, yarivus commented on content/en/interop-raw/interop-api/calling.md
> +In the first step for creating a proxy object you needed to provide the coordinates
```suggestion
In the first step for creating a proxy object, you needed to provide the coordinates
```

2023-08-28 09:15 UTC, yarivus commented on content/en/interop-raw/interop-api/calling.md
> +The registration process is an administrative task. For more information, see [TODO link].
placeholder TODO comment

2023-08-28 09:35 UTC, yarivus commented on content/en/interop-raw/interop-api/calling.md
> +The registration process is an administrative task. For more information, see [Interoperability Administration and Identity Management Guide](../interop-admin).
shouldn't this be using `relref` ?

2024-04-24 10:34 UTC, closed without merging