Nadinequinr3/doc 5706/update glossary p2p link manager
corda/corda-docs-portal pull request #1624
Opened 2023-08-03 14:26 UTC by nadinequinr3

- Clarified usage of the following:
  - REST Gateway
  - REST Gateway worker
  - P2P Link Manager
  - P2P Link Manager worker
- Updated some term definitions that were long for tooltips
- Added use of "REST user identity" (https://r3-cev.atlassian.net/browse/DOC-5707)
- Changed worker to lowercase

2023-08-03 15:06 UTC, paulmoloneyr3 requested changes

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "more": "<ul><li>The CorDapp API enables developers using Corda to develop CorDapps by accessing data or functionality from a remote service or application, without needing to understand the
```suggestion
        "more": "<ul><li>The CorDapp API enables developers using Corda to develop CorDapps by accessing data or functionality from a remote service or application, without needing to understand the underlying implementation details. For more information see the <a href=\"../developing-applications/api.html\"> CorDapp API documentation</a>.</li><li>The Corda REST API enables you to interact with your CorDapp; for example, to start a flow or retrieve the result of a flow. This API is exposed as a REST service. For more information see the <a href=\"../reference/rest-api.html\"> Corda REST API documentation</a>.</li>"
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "more": "The gateway workers are the only component of the cluster with access to the wider network and transfer Link Manager session messages taken from Kafka, then using HTTPS POST to send
```suggestion
        "more": "The gateway workers are the only component of the cluster with access to the wider network, and transfer Link Manager session messages taken from Kafka, then use HTTPS POST to send them to the peer's gateway worker. After local validation is received, messages are placed onto Kafka for the Link Manager to process. The gateway workers play the important role of establishing and validating the TLS links established to peer Corda Clusters and accessing external resources such as certificate revocation servers, or border proxies. Gateway workers have no direct access to any keys and can only request that the crypto workers sign the TLS handshake data via a specific Kafka topic. Crucially, the gateway worker has no ability to access the keys used in the Ledger, or by the Link Manager."
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
>          "more": "The Link Manager uses the data provided to it by the membership worker to translate virtual node names on CorDapp packets to physical HTTPS destination addresses and requests the gat
```suggestion
        "more": "The Link Manager uses the data provided to it by the membership worker to translate virtual node names on CorDapp packets to physical HTTPS destination addresses and requests the gateway worker to transmit its secured packets to the peers. If packets cannot be delivered, the Link Manager also manages redelivery, possibly via alternate gateway workers."
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "definition": "A worker that manages the secure transmission of packets to peers. The main functional component is the Link Manager which establishes end-to-end secure sessions for virtual no
```suggestion
        "definition": "A worker that manages the secure transmission of packets to peers. The main functional component is the Link Manager, which establishes end-to-end secure sessions for virtual nodes to communicate over.",
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "definition": "A worker that exposes the intranet HTTPS REST control ports of the Corda cluster. The REST workers support all of the dynamic administration APIs of the cluster, such as APIs t
```suggestion
        "definition": "A worker that exposes the intranet HTTPS REST control ports of the Corda cluster. The REST workers support all of the dynamic administration APIs of the cluster, such as APIs to configure the cluster, set up user role based permissions, or create and register virtual nodes. ",
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "more": "REST workers also provide the virtual node endpoint APIs for invoking the flows and the ledger applications and retrieving their status/results. All REST calls must be authenticated
```suggestion
        "more": "REST workers also provide the virtual node endpoint APIs for invoking the flows and the ledger applications, and for retrieving their status/results. All REST calls must be authenticated and authorized, typically using OAUTH2 for login/authentication and Role Based Access Controls checked against a user permissions database."
```

2023-08-03 15:06 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "definition": "In the context of X.509 certificates, revocation checks refer to the process of verifying whether a digital certificate is still valid and has not been revoked by the issuing C
```suggestion
        "definition": "In the context of X.509 certificates, revocation checks refer to the process of verifying if a digital certificate is still valid and has not been revoked by the issuing Certificate Authority (CA). ",
```

2023-08-03 15:20 UTC, nadinequinr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "more": "The gateway workers are the only component of the cluster with access to the wider network and transfer Link Manager session messages taken from Kafka, then using HTTPS POST to send
What about? 
```suggestion
        "more": "The gateway workers are the only component of the cluster with access to the wider network. The workers transfer Link Manager session messages taken from Kafka and use HTTPS POST to send them to the peer's gateway worker. After local validation is received, messages are placed onto Kafka for the Link Manager to process. The gateway workers play the important role of establishing and validating the TLS links established to peer Corda Clusters and accessing external resources such as certificate revocation servers, or border proxies. Gateway workers have no direct access to any keys and can only request that the crypto workers sign the TLS handshake data via a specific Kafka topic. Crucially, the gateway worker has no ability to access the keys used in the Ledger, or by the Link Manager."
```

2023-08-03 15:25 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0/glossaryitems.json
> +        "more": "The gateway workers are the only component of the cluster with access to the wider network and transfer Link Manager session messages taken from Kafka, then using HTTPS POST to send
Yep that works!

2023-08-03 20:40 UTC, yarivus approved these changes
LGTM

2023-08-04 09:40 UTC, paulmoloneyr3 approved these changes

2023-08-04 09:52 UTC, merged