Update Bootstrapping Corda Enterprise
corda/corda-docs-portal pull request #1636
Opened 2023-08-09 09:28 UTC by nadinequinr3

- Broke Manual Bootstrapping database section in subsections
- Added Enterprise-specific examples
- Other minor edits including fixing links and typos

2023-08-09 09:54 UTC, davidcurrie requested changes

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
> +The passwords for the `RBAC` and `CRYPTO` schemas and `VNODES` database must be available in Vault before Corda is deployed. These must be available in the Vault `dbsecrets` path, under the keys `rba
I know it's not something you've changed but I suspect that `dbsecrets` here is whatever you've provided for `createdSecretPath`.

@dickon - can you confirm?

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
> +If you are deploying Corda Enterprise, you must disable automatic bootstrapping and manually configure the database. For more information, see the [Database]({{< relref "./manual-bootstrapping.md#dat
There may be other reasons for using Enterprise beyond using Vault...
```suggestion
If you are deploying Corda Enterprise with HashiCorp Vault, you must disable automatic bootstrapping and manually configure the database. For more information, see the [Database]({{< relref "./manual-bootstrapping.md#database" >}})  section in the [Manual Bootstrapping]({{< relref "./manual-bootstrapping.md" >}}) section.
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +If you are deploying Corda Enterprise, you must disable automatic bootstrapping and manually configure the database, as described in this section.
```suggestion
If you are deploying Corda Enterprise with HashiCorp Vault, you must disable automatic bootstrapping and manually configure the database, as described in this section.
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +    enabled: false
```suggestion
bootstrap:
  db:
    enabled: false
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +* [RBAC Database Connection Configuration for Corda Enterprise](#rbac-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```suggestion
* [RBAC Database Connection Configuration for Corda Enterprise with HashiCorp Vault](#rbac-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +#### RBAC Database Connection Configuration for Corda Enterprise {{< enterprise-icon >}}
```suggestion
#### RBAC Database Connection Configuration for Corda Enterprise with HashiCorp Vault {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +      --jdbc-pool-max-size <POOL-SIZE> -t VAULT --vault-path dbsecrets --key rbac -l /tmp/db
Again, I think `dbsecrets` in these commands just needs to match whatever they give in their configuration overrides so we should probably show this as a variable. You already call out that this configuration needs to match what is in the overrides.

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +#### Crypto Database Connection Configuration for Corda Enterprise {{< enterprise-icon >}}
```suggestion
#### Crypto Database Connection Configuration for Corda Enterprise with HashiCorp Vault {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +* [Crypto Database Connection Configuration for Corda Enterprise](#crypto-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```suggestion
* [Crypto Database Connection Configuration for Corda Enterprise with HashiCorp Vault](#crypto-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +* [Virtual Nodes Database Connection Configuration for Corda Enterprise](#virtual-nodes-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```suggestion
* [Virtual Nodes Database Connection Configuration for Corda Enterprise with HashiCorp Vault](#virtual-nodes-database-connection-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +* [Initial Crypto Configuration for Corda Enterprise](#initial-crypto-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```suggestion
* [Initial Crypto Configuration for Corda Enterprise with HashiCorp Vault](#initial-crypto-configuration-for-corda-enterprise) {{< enterprise-icon >}}
```

2023-08-09 09:54 UTC, davidcurrie commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +#### Initial Crypto Configuration for Corda Enterprise {{< enterprise-icon >}}
```suggestion
#### Initial Crypto Configuration for Corda Enterprise with HashiCorp Vault {{< enterprise-icon >}}
```

2023-08-09 10:10 UTC, yarivus approved these changes
LGTM

2023-08-09 10:10 UTC, AnnaK-R3 requested changes

2023-08-09 10:10 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +1. Use the Corda CLI to generate DML files for creating the database tables to use for each of the crypto, config, and rbac components.
"crypto", "config" and "rbac" not capitalized because you're talking about components here?

2023-08-09 10:10 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   There is no schema in `--jdbc-url` as virtual  nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration not DML.
```suggestion
   There is no schema in `--jdbc-url` as virtual nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration not DML.
```

2023-08-09 10:10 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +#### Virtual Nodes Database Connection Configuration for Corda Enterprise {{< enterprise-icon >}}
```suggestion
#### Virtual Nodes Database Connection Configuration for Corda Enterprise with HashiCorp Vault {{< enterprise-icon >}}
```

2023-08-09 10:10 UTC, AnnaK-R3 commented on content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   There is no schema in `--jdbc-url` as virtual  nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration not DML.
```suggestion
   There is no schema in `--jdbc-url` as virtual nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration not DML.
```

2023-08-09 10:13 UTC, yarivus approved these changes
LGTM

2023-08-09 10:18 UTC, yarivus approved these changes
LGTM

2023-08-09 10:20 UTC, yarivus approved these changes
LGTM

2023-08-09 10:27 UTC, yarivus approved these changes
LGTM

2023-08-11 07:38 UTC, davidcurrie approved these changes
LGTM!

2023-08-11 08:13 UTC, AnnaK-R3 approved these changes

2023-08-11 08:17 UTC, merged

2023-08-11 12:43 UTC, yarivus reviewed
thx @nadinequinr3