making landing page cards clickable
corda/corda-docs-portal pull request #1690
Opened 2023-08-31 17:45 UTC by colin-hillis

Our landing page cards are clickable, yet the click doesn't lead anywhere. Instead, the links are buttons within the card <p> element. This is not very intuitive. As part of a larger set of potential changes to landing page:

1. Cards with one link are now entirely clickable.
2. The C5 card title was **Corda 5.0**, whereas the C4 card was **Corda 4**. The C5 card is now **Corda 5**.
3. The two highlighted cards (red) are not external links any more. The external symbol is removed accordingly.
4. The highlighted card (blue) is still external, but there was a problem adding the external symbol AND making the entire card clickable. For now, I have run with making the entire clickable and I have a question in with FE team around adding the external symbol too.
<img width="1465" alt="image" src="https://github.com/corda/corda-docs-portal/assets/112863914/a17d64be-3fc5-4fd0-b30a-c0cf4fdb3095">

2023-09-01 06:52 UTC, nadinequinr3 commented on themes/doks/layouts/index.html
> +            <a href="en/api-ref.html" class="btn rounded stretched-link">API references</a>
```suggestion
            <a href="en/api-ref.html" class="btn rounded stretched-link">API References</a>
```

2023-09-01 09:17 UTC, colin-hillis commented
Preview site will not build currently. Here is video of clickable cards:

https://github.com/corda/corda-docs-portal/assets/112863914/90b31240-36c2-49fa-9956-76a49571cf27

2023-09-01 09:25 UTC, nadinequinr3 requested changes
There is some inconsistencies with the buttons at the bottom of the cards but I wonder are they actually necessary anyway if the cards are clickable?

2023-09-01 09:25 UTC, nadinequinr3 commented on themes/doks/layouts/index.html
> +            <a href="en/tools.html" class="btn rounded stretched-link">Explore tools and add-ons</a>
```suggestion
            <a href="en/tools.html" class="btn rounded stretched-link">Explore Tools & Add-Ons</a>
```

2023-09-01 09:25 UTC, nadinequinr3 commented on themes/doks/layouts/index.html
> +            <a href="https://developer.r3.com" target="_blank" class="btn rounded stretched-link">Join R3 Developers</a>
```suggestion
            <a href="https://developer.r3.com" target="_blank" class="btn rounded stretched-link">Join the R3 Developer Community</a>
```

2023-09-01 09:25 UTC, nadinequinr3 commented on themes/doks/layouts/index.html
> +            <a href="en/api-ref.html" class="btn rounded stretched-link">API References</a>
The other labels all have verbs.. Should this be "Read API References" or similar?

2023-09-01 16:34 UTC, nadinequinr3 approved these changes
Much better 👍

2023-09-01 17:39 UTC, merged

2023-09-04 13:28 UTC, yarivus reviewed
thx @colin-hillis