Add extra datasource properties to db bootstrap config
corda/corda-docs-portal pull request #1732
Opened 2023-10-04 15:16 UTC by nadinequinr3

2023-10-05 16:24 UTC, kyriathar reviewed
A few comments

2023-10-05 16:24 UTC, kyriathar commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   For information about the Corda CLI `initial-config` command's arguments, see the [Corda CLI reference]({{< relref "../../../reference/corda-cli/initial-config.md#create-db-config" >}}).
```suggestion
   For information about the Corda CLI `create-db-config` command's arguments, see the [Corda CLI reference]({{< relref "../../../reference/corda-cli/initial-config.md#create-db-config" >}}).
```

2023-10-05 16:24 UTC, kyriathar commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   For example::
```suggestion
   For example:
```

2023-10-05 16:24 UTC, kyriathar commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   There is no schema in `--jdbc-url` as virtual nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration not DML. For more information about the Corda CLI `cr
Should we separate the addition a bit, perhaps a new line

2023-10-05 16:24 UTC, kyriathar commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   There is no schema in `--jdbc-url` as virtual nodes create their own schemas. However, `--is-admin` is required as this is a DDL configuration, not DML. For more information about the Corda CLI `c
Same as above about putting in a new line

2023-10-05 16:24 UTC, kyriathar commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   For information about the Corda CLI `topic` command's arguments, see the [Corda CLI reference]({{< relref"../../../reference/corda-cli/topic.md">}}).
Should we put this after showcasing the use of `topic` command so that we are aligned with other cases.

2023-10-09 07:35 UTC, kyriathar submitted a review, later dismissed

2023-10-09 08:10 UTC, paulmoloneyr3 requested changes

2023-10-09 08:10 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md
> +   ### Topic Creation by Direct Connection
Think this indentation is a typo?

2023-10-09 11:45 UTC, paulmoloneyr3 approved these changes

2023-10-09 11:53 UTC, merged