DOC-5987: Added missing parameter and updated some default Corda config fields
corda/corda-docs-portal pull request #1770
Opened 2023-10-20 10:54 UTC by AnnaK-R3

2023-10-24 09:30 UTC, rick-r3 requested changes
Only one of the `batchTimeOutMs` needs updating.  I've commented on the ones that should be reverted.

Rest of it looks good.

2023-10-24 09:30 UTC, rick-r3 commented on content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md
> +    * *Default:* 1
This one remains the same.

2023-10-24 09:30 UTC, rick-r3 commented on content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md
> +      * *Default:* 1
This one remains the same.

2023-10-24 10:29 UTC, AnnaK-R3 commented on content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md
> +    * *Default:* 1
updated

2023-10-24 10:29 UTC, AnnaK-R3 commented on content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md
> +      * *Default:* 1
updated

2023-10-25 08:00 UTC, rick-r3 approved these changes

2023-10-25 13:46 UTC, paulmoloneyr3 requested changes

2023-10-25 13:46 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md
> +The *absolute value* of *cryptoServiceFlowRetryCount* determines the number of times that the flow is retried. The *sign* of the value determines what happens when all retries are exhausted:
```suggestion
The *absolute value* of `cryptoServiceFlowRetryCount` determines the number of times that the flow is retried. The *sign* of the value determines what happens when all retries are exhausted:
```

2023-10-25 13:51 UTC, paulmoloneyr3 approved these changes

2023-10-25 14:03 UTC, merged