Isolated state manager
corda/corda-docs-portal pull request #1847
Opened 2023-11-15 15:06 UTC by nadinequinr3

2023-11-20 09:27 UTC, paulmoloneyr3 requested changes

2023-11-20 09:27 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +If the pre-install checks fail, for example, if Kafka or PostgreSQL are not available, you can retrieve the logs for a single pod using `kubectl`. For more information on retrieving the logs, see the
```suggestion
If the pre-install checks fail (for example, if Kafka or PostgreSQL are not available), you can retrieve the logs for a single pod using `kubectl`. For more information on retrieving the logs, see the [Logs]({{< relref "../../observability/logs.md" >}}) section.
```

2023-11-20 09:34 UTC, paulmoloneyr3 submitted a review, later dismissed

2023-11-20 10:48 UTC, conalsmith-r3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +Corda requires one or more PostgreSQL database instances for the persistence of state between worker types. These are referred to as state manager databases. R3 recommends that you deploy separate is
`persistence of state between worker types` isn't quite correct, it probably should be 

"Corda requires one or more PostgreSQL database instances for the persistence of state."

2023-11-20 12:40 UTC, nadinequinr3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +If you do not configure state manager databases, Corda deploys the state managers for the flow, flow mapper, and token selection workers on the cluster database. This is not safe for production deplo
So do we need a section before https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.html#create-the-database-tables to say that you must manually create separate state manager database instances for the 3 worker types?

2023-11-20 13:42 UTC, conalsmith-r3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +If you do not configure state manager databases, Corda deploys the state managers for the flow, flow mapper, and token selection workers on the cluster database. This is not safe for production deplo
Well we already say just above it:

```
Corda requires one or more PostgreSQL database instances for the persistence of state. These are referred to as state manager databases. R3 recommends that you deploy separate isolated state manager database instances for the following workers:
```

And in manual bootstrapping we say:

```
Review the DML file generated and execute it against each of the State Manager databases.
```

Maybe all we need to say is, 
```
If you do not configure state manager databases and you have auto-bootstrapping enabled, Corda helm installation will deploy the state managers for the flow, flow mapper, and token selection workers on the cluster database. This is not safe for production deployments.
```

2023-11-21 09:39 UTC, conalsmith-r3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +If you do not configure state manager databases, Corda deploys the state managers for the flow, flow mapper, and token selection workers on the cluster database. This is not safe for production deplo
Let's leave it as is, as you say this whole page assumes auto-bootstrapping is used

2023-11-21 11:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
> +If you do not configure state manager databases, Corda deploys the state managers for the flow, flow mapper, and token selection workers on the cluster database. This is not safe for production deplo
Done

2023-11-22 11:12 UTC, paulmoloneyr3 approved these changes

2023-11-22 11:14 UTC, conalsmith-r3 approved these changes
lgtm

2023-11-23 11:13 UTC, merged