DOC-6145: 4.11 pre-release technical review
corda/corda-docs-portal pull request #1886
Opened 2023-11-29 12:51 UTC by AnnaK-R3

2023-11-29 13:53 UTC, colljos approved these changes
LGTM

2023-11-29 15:57 UTC, adelel1 approved these changes

2023-11-30 13:11 UTC, paulmoloneyr3 requested changes

2023-11-30 13:41 UTC, rick-r3 commented on content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md
>  For more information, see [Available Network Parameters]({{< relref "network/available-network-parameters.md" >}}).
Can we add something that say that setting these will require CENM 1.6 or later, please.

2023-11-30 14:26 UTC, paulmoloneyr3 approved these changes

2023-11-30 14:28 UTC, merged