Contract Testing Updates: version 2
corda/corda-docs-portal pull request #2115
Opened 2024-04-09 15:47 UTC by nadinequinr3

Preview: https://nadine.preview.docs.r3.com/en/tools-corda5/contract-testing.html

2024-04-09 16:24 UTC, nkovacsx approved these changes

2024-04-09 16:51 UTC, paulmoloneyr3 requested changes

2024-04-09 16:51 UTC, paulmoloneyr3 commented on content/en/tools-corda5/contract-testing/examples.md
> +This examples uses the same state as the [example with no service injection](#no-service-injection) but changes the contract to have an injectable service and an extra verification based on that serv
```suggestion
This example uses the same state as the [example with no service injection](#no-service-injection) but changes the contract to have an injectable service and an extra verification based on that service. In this example, we check the default digest algorithm that the `DigestService` returns. The rest of the contract code remains the same:
```

2024-04-09 16:51 UTC, paulmoloneyr3 commented on content/en/tools-corda5/contract-testing/examples.md
> +This is a basic example, for illustration purposes only, and not production-ready code. The state and contract code is written in Kotlin.
```suggestion
This is a basic example for illustration purposes only, and not production-ready code. The state and contract code is written in Kotlin.
```

2024-04-10 11:11 UTC, paulmoloneyr3 approved these changes

2024-04-10 11:13 UTC, merged