DOC-6357: Updated platform version for Corda 4.12
corda/corda-docs-portal pull request #2167
Opened 2024-06-21 16:18 UTC by AnnaK-R3

2024-06-21 18:52 UTC, chriscochrane approved these changes

2024-06-24 09:10 UTC, paulmoloneyr3 requested changes

2024-06-24 09:10 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/community/app-upgrade-notes.md
> +Additionally, if a CorDapp has been updated to platform version 140, you must upgrade Corda node to Corda 4.12. For instructions on how to upgrade Corda nodes, see [Corda Community Edition 4.11 to 4.
```suggestion
Additionally, if a CorDapp has been updated to platform version 140, you must upgrade Corda nodes to Corda 4.12. For instructions on how to upgrade Corda nodes, see [Corda Community Edition 4.11 to 4.12 upgrade guide]({{< relref "comm-upgrade-guide.md" >}}).
```

2024-06-24 09:10 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/enterprise/app-upgrade-notes.md
> +Additionally, if a CorDapp has been updated to platform version 140, you must upgrade Corda node to Corda 4.12. For instructions on how to upgrade Corda nodes, see [Corda Enterprise Edition 4.11 to 4
```suggestion
Additionally, if a CorDapp has been updated to platform version 140, you must upgrade Corda nodes to Corda 4.12. For instructions on how to upgrade Corda nodes, see [Corda Enterprise Edition 4.11 to 4.12 upgrade guide]({{< relref "upgrade-guide.md" >}}).
```

2024-06-24 09:35 UTC, merged