DOC-6248: Corda 4.12 version update
corda/corda-docs-portal pull request #2170
Opened 2024-06-24 11:16 UTC by AnnaK-R3

2024-06-24 15:20 UTC, tomstark99 requested changes
I am still waiting on feedback on which HSM driver versions were used in testing but these changes can be done now already

2024-06-24 15:20 UTC, tomstark99 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
>  {{< warning >}}
Remove this warning block

2024-06-24 15:20 UTC, tomstark99 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
Line 38, does not support java 18 or higher

2024-06-25 10:16 UTC, AnnaK-R3 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
> +Corda Enterprise Edition 4.12 has been tested and verified to work with **Oracle JDK 8 JVM 8u381** and **Azul Zulu Enterprise 8u382**, for Azure deployment downloadable from
Updated

2024-06-25 10:16 UTC, AnnaK-R3 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
>  {{< warning >}}
Removed

2024-06-25 10:17 UTC, AnnaK-R3 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
Removed and updated

2024-06-25 10:18 UTC, AnnaK-R3 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
Updated

2024-06-25 13:30 UTC, tomstark99 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
> +|[Zulu OpenJDK](https://www.azul.com/)|17.0.9|
_Sorry_ Anna, 

|[Oracle JDK](https://www.oracle.com/ie/java/technologies/downloads/)|17.0.9|

needs to be added back in now

2024-06-25 14:46 UTC, AnnaK-R3 commented on content/en/platform/corda/4.12/enterprise/platform-support-matrix.md
>  {{< warning >}}
Removed

2024-06-27 12:33 UTC, paulmoloneyr3 approved these changes

2024-06-27 12:43 UTC, merged