DOC-6566: Corda 4.12.2 release notes
corda/corda-docs-portal pull request #2243
Opened 2024-11-04 11:39 UTC by AnnaK-R3

Preview OS: https://niamh.preview.docs.r3.com/en/platform/corda/4.12/community/release-notes.html#corda-open-source-edition-4122-release-notes
Preview ENT: https://niamh.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4122-release-notes

2024-11-10 19:16 UTC, adelel1 commented
Hi @AnnaK-R3 / @paulmoloneyr3 
I have updated the release notes and pushed a commit (I removed the new features section and added as fixed issues - as its a patch release). All the updates are in the commit.
I also added a third party component upgrades table, however it needs updating with the correct dependency name and name similar to what we did in original 4.12 release.
@chriscochrane Please see above, can you provide Anna/Paul with the info for the third party upgrades table, plus any missed. This is for OS and ENT. Similar to what we did for the initial release.

2024-11-11 12:32 UTC, adelel1 submitted a review, later dismissed

2024-11-11 14:59 UTC, paulmoloneyr3 requested changes

2024-11-11 14:59 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md
> +* An open telemetry span has been added around the send to multiple parties and receive from multiple parties operations.
```suggestion
* An open telemetry span has been added around the Send to Multiple Parties and Receive from Multiple Parties operations.
```

2024-11-11 14:59 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md
> +* It is now possible to create two nodes whose X.500 names has the same O field value but different OU values when using the driver DSL for testing.
```suggestion
* It is now possible to create two nodes whose X.500 names have the same Organisation (O) field value but different Organisation Unit (OU) values when using the driver DSL for testing.
```

2024-11-11 14:59 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md
> +* There's no longer a memory leak when creating a series of mock networks for testing purposes.
```suggestion
* There is no longer a memory leak when creating a series of mock networks for testing purposes.
```

2024-11-11 15:18 UTC, paulmoloneyr3 submitted a review, later dismissed

2024-11-11 15:18 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.12/community/release-notes.md
> +* It is now possible to create two nodes whose X.500 names have the same O field value but different OU values when using the driver DSL for testing.
```suggestion
* It is now possible to create two nodes whose X.500 names have the same Organisation (O) field value but different Organisation Unit (OU) values when using the driver DSL for testing.
```

2024-11-11 15:20 UTC, paulmoloneyr3 approved these changes

2024-11-11 16:00 UTC, merged