DOC-3086 Added more direct detail pointing to the advice on archive-friendly cordapps
corda/corda-docs-portal pull request #272
Opened 2021-10-07 11:37 UTC by benpesterr3

DOC-3086 Added more direct detail pointing to the advice on archive-friendly cordapps

2021-10-07 12:13 UTC, ivanterziev-r3 requested changes
Just a tiny typo fix in two places and it's good to go

2021-10-07 12:13 UTC, ivanterziev-r3 commented on content/en/platform/corda/4.8/enterprise/node/archiving/archiving-setup.md
> +Unless you follow the guide for [making Archive-friendly CorDapps](#making-archive-friendly-cordapps)This can cause:
```suggestion
Unless you follow the guide for [making Archive-friendly CorDapps](#making-archive-friendly-cordapps), this can cause:
```

2021-10-07 12:13 UTC, ivanterziev-r3 commented on content/en/platform/corda/4.7/enterprise/node/archiving/archiving-setup.md
> +Unless you follow the guide for [making Archive-friendly CorDapps](#making-archive-friendly-cordapps)This can cause:
```suggestion
Unless you follow the guide for [making Archive-friendly CorDapps](#making-archive-friendly-cordapps), this can cause:
```

2021-10-14 15:27 UTC, erinking-r3 commented on content/en/platform/corda/4.7/enterprise/node/archiving/archiving-setup.md
> +Due to its in-memory design, the Archive Service is most effective and efficient for smaller ledgers & frequent archiving events. For scenarios that don't fit these constraints, you should consider b
```suggestion
Due to its in-memory design, the Archive Service is most effective and efficient for smaller ledgers & frequent archiving events. For scenarios that don't fit these constraints, you should consider building your required archiving logic within the application itself. This introduction includes advice on [making your CorDapps archive-friendly](#making-archive-friendly-cordapps).
```

2021-10-15 09:03 UTC, merged