DOC-3878 Clarified Log4j OS updates in alerts and releases page
corda/corda-docs-portal pull request #563
Opened 2022-02-15 10:57 UTC by michelemarsden

2022-02-15 12:38 UTC, benpesterr3 requested changes
I think we need to check what the fixes are in here with @sachingokhale before removing the update from December 16th. That update was checked and signed off on that date so I'm not sure it was completely wrong.

2022-02-16 11:20 UTC, michelemarsden commented
> I think we need to check what the fixes are in here with @sachingokhale before removing the update from December 16th. That update was checked and signed off on that date so I'm not sure it was completely wrong.

Looking at the repo, OS 4.3 hasn't been fixed. Nothing has been pushed to that branch since 2019. https://github.com/corda/corda/commits/release-os-4.3

2022-02-16 11:42 UTC, erinking-r3 approved these changes

2022-02-16 13:23 UTC, benpesterr3 approved these changes
As long as this is confirmed at the right level, I approve.

2022-02-16 13:38 UTC, merged