ENT-6490: Update Node Docker instruction for OS 4.9
corda/corda-docs-portal pull request #625
Opened 2022-05-24 18:44 UTC by pmck91

An update to @vkolomeyko pull request [624](https://github.com/corda/corda-docs-portal/pull/624).

2022-05-25 08:40 UTC, vkolomeyko commented
Looks fine to me, however CI build fails at the moment:
```
[2022-05-24T19:00:27.342Z] Error: Error building site: "/src/content/en/platform/corda/4.9/community/node-docker-deployments.md:6:1": failed to unmarshal YAML: yaml: line 5: mapping values are not allowed in this context
```
This is likely to be caused by spaces removed in the header of the file.

2022-05-25 08:41 UTC, vkolomeyko requested changes
.

2022-05-26 12:26 UTC, vkolomeyko submitted a review, later dismissed
LGTM

2022-05-31 07:59 UTC, nadinequinr3 requested changes

2022-05-31 07:59 UTC, nadinequinr3 commented on content/en/platform/corda/4.9/community/node-docker-deployments.md
> +Once the container has finished performing the initial registration, it is necessary to initialize node's DB as follows:
you must initialize the node's DB as follows:

2022-05-31 07:59 UTC, nadinequinr3 commented on content/en/platform/corda/4.9/community/node-docker-deployments.md
> +After that the node can be started as normal:
You can now start the node as normal:

2022-05-31 08:54 UTC, nadinequinr3 approved these changes

2022-05-31 09:23 UTC, vkolomeyko approved these changes

2022-05-31 09:24 UTC, vkolomeyko commented
@nadinequinr3 @benpesterr3 - would you be able to merge this PR? (as I do not have permissions)

2022-06-01 06:45 UTC, merged