DOC-3918
corda/corda-docs-portal pull request #652
Opened 2022-08-25 15:59 UTC by amiegrace12

Updated case insensitivity information in CENM 1.5 database-set-up file

2022-08-25 19:32 UTC, yarivus approved these changes
LGTM

2022-08-31 16:16 UTC, amosmwsmith approved these changes

2022-09-07 09:22 UTC, yarivus approved these changes
LGTM

2022-09-07 10:39 UTC, nadinequinr3 requested changes

2022-09-07 10:39 UTC, nadinequinr3 commented on content/en/platform/corda/1.5/cenm/database-set-up.md
> +The database collation for SQL Server can be case insensitive, but case differences in node-info will be treated by CENM as if they were for different nodes. See [Collations and Case Sensitivity docu
```suggestion
The database collation for SQL Server can be case insensitive, but CENM treats case differences in `node-info` as if they were for different nodes. See [Collations and Case Sensitivity documentation](https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity) for more information.
```

2022-09-07 11:04 UTC, yarivus approved these changes
LGTM

2022-09-07 11:27 UTC, nadinequinr3 approved these changes

2022-09-07 11:30 UTC, merged