CORE-6308 Add Local Kubernetes deployment
corda/corda-docs-portal pull request #660
Opened 2022-09-16 07:33 UTC by davidcurrie

Content predominantly sourced from https://github.com/corda/corda-runtime-os/wiki/Local-development-with-Kubernetes with updates to reflect changes in Docker Desktop and to remove content that is only applicable to Corda development.

Further updates will probably be needed to link this together with other content (e.g. for subsequent actions to upload a CPI, execute flows, ...) when it is available.

2022-09-16 08:14 UTC, yarivus reviewed
@davidcurrie / @colin-hillis / @nadinequinr3 
Should we be seeing these :
![image](https://user-images.githubusercontent.com/104990295/190590416-f096a473-0bb0-457c-b306-97ca06d80230.png)

2022-09-16 08:18 UTC, davidcurrie commented
> @davidcurrie / @colin-hillis / @nadinequinr3 Should we be seeing these : ![image](https://user-images.githubusercontent.com/104990295/190590416-f096a473-0bb0-457c-b306-97ca06d80230.png)

I was just following the example in https://r3-cev.atlassian.net/wiki/spaces/CB/pages/3767173243/Style+guide+for+technical+writing#Code-Blocks. I believe this is Hugo specific so won't show up in a GitHub preview. Let me know if it should be removed though.

2022-09-16 10:39 UTC, nadinequinr3 commented
Yes, the tabs are formatted by Hugo so wouldn't expect them to display correctly here. However, I have a feeling Hugo won't like the additional line breaks so will investigate that.

2022-09-16 10:41 UTC, davidcurrie commented
> Yes, the tabs are formatted by Hugo so wouldn't expect them to display correctly here. However, I have a feeling Hugo won't like the additional line breaks so will investigate that.

That would be amusing as I only added them because the Markdown linter in my IDE insists that code blocks should be surrounded by empty lines!

2022-09-16 15:21 UTC, nadinequinr3 commented
I think this piece will fit better under the "tutorials" section. I'm happy to move it after it's merged to the branch but I think then we still need a brief overview type piece for this section. Why you would deploy this way? The benefits/limitations etc

Just FYI 
![image](https://user-images.githubusercontent.com/103633799/190671182-7785cd25-fa44-4a35-9e8d-88930f78f61d.png)
I did some testing locally and the issue is with the indenting within the tabs shortcode.

2022-09-16 15:21 UTC, nadinequinr3 requested changes

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    ```bash
```suggestion
```bash
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    eval $(minikube docker-env)
```suggestion
eval $(minikube docker-env)
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    ```
```suggestion
```
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    ```pwsh
```suggestion
```pwsh
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    minikube docker-env --shell=powershell | Invoke-Expression
```suggestion
minikube docker-env --shell=powershell | Invoke-Expression
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    ```
```suggestion
```
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +**Note:** The commands that follow all assume that you are using a namespace called `corda`.
```suggestion
{{< note >}}
The commands that follow all assume that you are using a namespace called `corda`.
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +Modify the `-n corda` option on each `kubectl` command if you use a different namespace.
```suggestion
Modify the `-n corda` option on each `kubectl` command if you use a different namespace.
{{< /note >}}
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +    The `--wait` option ensures all of the pods are ready before returning and the `--render-subchart-notes` option gives you a brief overview of the connection details.
```suggestion
    The `--wait` option ensures all of the pods are ready before returning. The `--render-subchart-notes` option gives you a brief overview of the connection details.
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +The Corda Docker images need to be built from source.
```suggestion
The Corda Docker images must be built from source.
```

2022-09-16 15:21 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-dev-preview-2/deploying/local-deployment.md
> +When the commmand completes, the RPC endpoint should ready to access.
```suggestion
When the commmand completes, the RPC endpoint should be ready to access.
```

2022-09-16 15:31 UTC, davidcurrie commented
We'll see what it does with the numbering. I'd rather have the code indented correctly under  the numbering than have the tabs if it comes to it.

Happy to see this move under tutorials. I suspect you may end up dropping the whole `deploying` section for DP2.

It will be easier to add the introduction once the other material is in place as I can then cross link to what they probably should be doing instead. (The approach documented is a bit of a stop-gap until we have something better in the beta.)

2022-09-16 16:29 UTC, nadinequinr3 commented
> We'll see what it does with the numbering. I'd rather have the code indented correctly under the numbering than have the tabs if it comes to it.
> 
Sorry, once the {{ tabs }} part is indented the whole piece will be:

![image](https://user-images.githubusercontent.com/103633799/190686220-4d7b1d00-d0ea-4eb5-9a74-1ae65272145d.png)

2022-09-16 16:32 UTC, davidcurrie commented
Oh - great. That's perfect.

2022-09-16 16:39 UTC, davidcurrie commented
Has the `C5-DP2` branch got rewritten at some point? I seem to have got a stack of commits on my PR branch that no longer appear on that branch and now lead to a pile of conflicts. Should I just close this and start again?

2022-09-16 18:13 UTC, nadinequinr3 commented
There would have been a lot of commits to those files listed (except local-deployment) over the last few days and CP5-DP2 was also rebased with main but I'm not sure why we're seeing conflicts. Your changes were all in that one file, right?

2022-09-16 18:14 UTC, nadinequinr3 commented
If it's ok with you, it might be cleanest/safest/fastest for me to just copy the contents with your latest changes to the branch directly? I want to add it to the file under "Tutorials" anyway..

2022-09-18 21:24 UTC, davidcurrie commented
> If it's ok with you, it might be cleanest/safest/fastest for me to just copy the contents with your latest changes to the branch directly? I want to add it to the file under "Tutorials" anyway..

It'll be the rebase that's the problem. Sure - I'm fine with you just copying the contents and, yes, all my changes are in the one file.

2022-09-19 07:56 UTC, nadinequinr3 commented
You can view a preview here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0-dev-preview-2/deploying/overview.html

2022-09-23 20:49 UTC, closed without merging