Various minor edits following a walkthrough of the Getting Started section
corda/corda-docs-portal pull request #696
Opened 2022-10-06 15:13 UTC by nadinequinr3

2022-10-07 08:44 UTC, paulmoloneyr3 requested changes

2022-10-07 08:44 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-dev-preview-2/getting-started/first-flow.md
> +There are other services, such as the `Persistence` and `Serialization` services, which are beyond the scope of this getting started example.
```suggestion
There are other services, such as the `Persistence` and `Serialization` services, which are beyond the scope of this Getting Started example.
```

I'm putting caps for this but still uncertain they should be used so I'll leave it up to you!

2022-10-07 08:44 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-dev-preview-2/getting-started/first-flow.md
> +   The response from the initiating flow is always a String, which can be returned when the flow status is queried by HTTP-RPC.
```suggestion
   The response from the initiating flow is always a string, which can be returned when the flow status is queried by HTTP-RPC.
```

2022-10-07 13:23 UTC, paulmoloneyr3 approved these changes

2022-10-07 13:56 UTC, merged

2022-10-08 11:18 UTC, yarivus reviewed
Thanks @nadinequinr3