Add Network Types info
corda/corda-docs-portal pull request #744
Opened 2022-11-15 12:12 UTC by nadinequinr3

2022-11-15 13:15 UTC, yarivus approved these changes
LGTM

2022-11-16 10:48 UTC, paulmoloneyr3 requested changes

2022-11-16 10:48 UTC, paulmoloneyr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-options/network-types.md
> +3. Package MGM `GroupPolicy.json` file into an MGM CPI.
```suggestion
3. Package the MGM `GroupPolicy.json` file into an MGM CPI.
```

2022-11-16 11:35 UTC, yarivus reviewed
LGTM along with @paulmoloneyr3 's comments

2022-11-16 12:01 UTC, AnnaK-R3 approved these changes

2022-11-16 12:23 UTC, yarivus submitted a review, later dismissed
LGTM

2022-11-16 12:36 UTC, colin-hillis requested changes

2022-11-16 12:36 UTC, colin-hillis commented on content/en/platform/corda/5.0-alpha/deploying/deployment-options/network-types.md
> +6. Assign required HSMs for the MGM.
Don't think HSM is previously defined in this doc. Do we need to?

2022-11-17 08:25 UTC, yarivus requested changes

2022-11-17 08:25 UTC, yarivus commented on content/en/platform/corda/5.0-alpha/deploying/deployment-options/network-types.md
> +6. Assign required hardware security models (HSMs) for the MGM.
Should be:
`Hardware Security Modules`
(capital letter per word and Modules instead of Models)

2022-11-17 10:24 UTC, charlieR3 reviewed
Looks good to me other than the item highlight by @yarivus (models -> modules)

2022-11-17 15:19 UTC, colin-hillis approved these changes
LGTM. Thanks Nadine

2022-11-17 17:18 UTC, paulmoloneyr3 approved these changes

2022-11-17 21:21 UTC, yarivus approved these changes
LGTM

2022-11-18 09:00 UTC, merged