Doc 4234 - Fixes to 4.9 upgrade procedure docs
corda/corda-docs-portal pull request #745
Opened 2022-11-15 12:21 UTC by paulmoloneyr3

Fixes to 4.9 upgrade procedure docs based on feedback from SBI via @yangbor3

2022-11-15 12:26 UTC, yarivus approved these changes
LGTM

2022-11-15 15:16 UTC, colin-hillis requested changes

2022-11-15 15:16 UTC, colin-hillis commented on content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
> +Make sure it’s available on your path, and that you’ve read the [Corda release notes](release-notes-enterprise.md). Pay particular attention to which version of Java the node requires.
...that the node requires.

2022-11-15 15:16 UTC, colin-hillis commented on content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
> +If you used Corda Shell in the previous version, put Corda Shell in the driver directory or use the standalone type Corda Shell according to Node shell.”
directory, or

(Also a stray " at end...???)

2022-11-15 15:19 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
> +Make sure it’s available on your path, and that you’ve read the [Corda release notes](release-notes-enterprise.md). Pay particular attention to which version of Java the node requires.
Done.

2022-11-15 15:19 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
> +If you used Corda Shell in the previous version, put Corda Shell in the driver directory or use the standalone type Corda Shell according to Node shell.”
Done.

2022-11-16 01:05 UTC, yangbor3 approved these changes

2022-11-17 13:20 UTC, colin-hillis approved these changes
LGTM. Thanks Paul

2022-11-17 15:50 UTC, merged

2022-11-17 21:30 UTC, yarivus reviewed
Thx @paulmoloneyr3