DOC-4185 Document manual bootstrapping
corda/corda-docs-portal pull request #746
Opened 2022-11-15 12:22 UTC by davidcurrie

2022-11-15 13:13 UTC, yarivus submitted a review, later dismissed
LGTM

2022-11-15 21:11 UTC, nadinequinr3 requested changes

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The following Corda CLI command generates DML files in the directory `/tmp/db` for creating the database schema:
```suggestion
2. Use the Corda CLI to generate DML files for creating the database schema. For example, the following command generates the files in the directory `/tmp/db`:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The following Corda CLI command generates DDL for populating the RBAC database connection configuration:
```suggestion
4. Execute the following Corda CLI command to generate DDL for populating the RBAC database connection configuration:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The DDL generated should be reviewed and then executed against the database.
```suggestion
5. Review the DDL files generated and then execute against the database.
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +An example usage might look as follows:
```suggestion
For example:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +### Create Crypto Database Connection Configuration
```suggestion

```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The following Corda CLI command generates DDL for populating the Crypto database connection configuration:
```suggestion
6. Execute the following Corda CLI command to generate DDL for populating the Crypto database connection configuration:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +An example usage might look as follows:
```suggestion
For example:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The DDL generated should be reviewed and then executed against the database.
```suggestion
7. Review the DDL files generated and then execute against the database.
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The following Corda CLI command generates DDL for populating the initial admin user for Corda:
```suggestion
8.Execute the following Corda CLI command to generate DDL for populating the initial admin user for Corda:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +### Create the Initial Admin User
```suggestion

```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The DDL generated should be reviewed and then executed against the database.
```suggestion
9. Review the DDL files generated and then execute against the database.
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +Create the RBAC and Crypto users and grant access as follows:
```suggestion
10. Create the RBAC and Crypto users and grant access as follows:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +### Create the Database Users and Grant Access
```suggestion

```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +### Create the Initial Crypto Configuration
```suggestion

```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The following Corda CLI command generates DDL for populating the initial crypto configuration:
```suggestion
11. Execute the following Corda CLI command to generate DDL for populating the initial crypto configuration:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +The DDL generated should be reviewed and then executed against the database.
```suggestion
12. Review the DDL files generated and then execute against the database.
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +Automatic creation of these RBAC roles can be disabled as follows:
```suggestion
1. Set the following override in the deployment configuration to disable the automatic creation:
```

2022-11-15 21:11 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-alpha/deploying/deployment-tutorials/manual.md
> +To manually create the three RBAC roles, execute the following three commands:
```suggestion
2. Execute the following three commands:
```

2022-11-15 22:07 UTC, nadinequinr3 submitted a review, later dismissed

2022-11-15 22:22 UTC, nadinequinr3 approved these changes

2022-11-15 22:31 UTC, merged

2022-11-16 11:00 UTC, yarivus reviewed
Thanks @nadinequinr3