DOC-4304: Added the default isolation level for database transactions in state persistence doc
corda/corda-docs-portal pull request #749
Opened 2022-11-16 08:23 UTC by amiegrace12

2022-11-16 10:59 UTC, yarivus submitted a review, later dismissed
LGTM

2022-11-16 12:22 UTC, yarivus submitted a review, later dismissed
LGTM

2022-11-16 15:03 UTC, paulmoloneyr3 requested changes

2022-11-16 15:03 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.6/enterprise/cordapps/state-persistence.md
> +Configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at database Level.
```suggestion
The configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at the database level.
```

2022-11-16 15:03 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.7/enterprise/cordapps/state-persistence.md
> +Configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at database Level.
```suggestion
The configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at the database level.
```

2022-11-16 15:03 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.8/enterprise/cordapps/state-persistence.md
> +Configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at database Level.
```suggestion
The configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at the database level.
```

2022-11-16 15:03 UTC, paulmoloneyr3 commented on content/en/platform/corda/4.9/enterprise/cordapps/state-persistence.md
> +Configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at database Level.
```suggestion
The configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at the database level.
```

2022-11-16 15:08 UTC, colin-hillis requested changes

2022-11-16 15:27 UTC, amiegrace12 commented on content/en/platform/corda/4.6/enterprise/cordapps/state-persistence.md
> +The configuration is set to `READ_COMMITED` by default, and it is not configurable. This is the best option for Corda operations at the database level.
Just checked and it's a typo, thanks for spotting it!

2022-11-16 15:55 UTC, yarivus reviewed
LGTM
thanks @amiegrace12 & @colin-hillis

2022-11-17 11:46 UTC, paulmoloneyr3 approved these changes

2022-11-17 13:23 UTC, colin-hillis approved these changes
Thanks for fixing that Nadine.

2022-11-17 16:31 UTC, merged