Mattb/beta 1.1 updates
corda/corda-docs-portal pull request #990
Opened 2023-01-31 13:52 UTC by mattbradburyr3

Updating the getting started docs for beta 1.1

2023-01-31 20:18 UTC, yarivus requested changes

2023-01-31 20:18 UTC, yarivus commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +2. Change to the new directory and checkout the beta 1 branch:
```suggestion
2. Change to the new directory and checkout the Beta 1 branch:
```
Or ...
```suggestion
2. Change to the new directory and checkout the 'release/corda-5-beta-1' branch:
```

2023-01-31 20:18 UTC, yarivus commented on content/en/platform/corda/5.0-beta/developing/getting-started/fast-feedback-with-the-simulator/fast-feedback-with-the-simulator.md
> +As of Beta 1.1 Simulator does not support the UTXOLedgerService, for now this limits the usefulness of the simulator for utxo based application.
```suggestion
As of Beta 1.1 Simulator does not support the UTXOLedgerService, for now this limits the usefulness of the simulator for UTXO based application.
```

2023-02-01 10:36 UTC, yarivus submitted a review, later dismissed
LGTM

2023-02-01 10:43 UTC, nadinequinr3 requested changes

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +These task help with the lifecycle of your local Corda Cluster.
```suggestion
These tasks help with the lifecycle of your local Corda cluster.
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +#### `startCorda`
```suggestion
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +`1-createGroupPolicy` creates the Group policy which is required to set up the Application Network.
```suggestion
`1-createGroupPolicy` creates the Group policy which is required to set up the application network.
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +`quickDeployCordapp` is just an alias for `5-createAndRegisterVNodes`, you should click this to do your first deployment of your Cordapp to a newly started cluster.
```suggestion
`quickDeployCordapp` is just an alias for `5-createAndRegisterVNodes`. You should click this to do your first deployment of your CorDapp to a newly started cluster.
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +You only need to run `quickDeployCordapp` the first time you upload your CPI to the corda cluster. On subsequent builds you can just click `4-deployCPIs`. This will reduce your turnaround time for de
```suggestion
You only need to run `quickDeployCordapp` the first time you upload your CPI to the corda cluster. On subsequent builds, you can just run `4-deployCPIs`. This reduces your turnaround time for deploying your code from 1-2 mins to around 20-30 seconds.
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
> +To Obtain the Corda Cli installer without the release pack:
```suggestion
To obtain the Corda CLI installer without the release pack:
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
> +To Obtain the Corda Cli installer without the release pack:
```suggestion
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
>  1. Download `platform-jars-Fox.tar.gz` from the [R3 Customer Hub](https://r3.force.com/).
```suggestion
1. Download `platform-jars-Fox.tar.gz` from the [R3 Customer Hub](https://r3.force.com/) or from the [R3 S3 repository](https://download.corda.net/packages/corda-cli-downloader/5.0.0.0-Fox1.1/corda-cli-downloader-5.0.0.0-Fox1.1.zip).
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
> +1. Download `platform-jars-Fox.tar.gz` from the R3 S3 repository [here](https://download.corda.net/packages/corda-cli-downloader/5.0.0.0-Fox1.1/corda-cli-downloader-5.0.0.0-Fox1.1.zip).
```suggestion
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
> +2. Extract the files.
```suggestion
```

2023-02-01 10:43 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/running-your-first-cordapp/run-first-cordapp.md
> +Currently, we do not have a liveness detector for Corda in the CSDE so we check liveness by manually hitting an endpoint. You can use the listVNodes helper for this.
```suggestion
Currently, we do not have a liveness detector for Corda in the CSDE so we check liveness by manually hitting an endpoint. You can use the [`listVNodes` helper](cordapp-standard-development-environment/csde.html#csde-queries) to do this.
```

2023-02-01 10:53 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +Note, corda takes around a minute to start up, however at present the gradle tasks shows as complete before the start up has finished. It is best to poll the cluster with one of the csde-query helper
```suggestion
Note, Corda takes about one minute to start up. However, at present, the Gradle task shows as complete before the start up has finished. It is best to poll the cluster with one of the `csde-query` helpers until it responds to confirm if the cluster is live and ready to interact.
```

2023-02-01 11:37 UTC, nadinequinr3 commented on content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
> +`3-buildCPIs` builds your Cordapp and wraps it in a signed CPI.
```suggestion
`3-buildCPIs` builds your CorDapp and wraps it in a signed CPI.
```

2023-02-01 12:12 UTC, yarivus submitted a review, later dismissed
LGTM

2023-02-01 12:40 UTC, nadinequinr3 approved these changes

2023-02-01 12:44 UTC, merged